"use client";

import { useEffect, useState } from "react";

type DirectionId = "women" | "men" | "diagnostics" | "beauty" | "family";

const phone = "+7 (861) 203-36-32";
const phoneHref = "tel:+78612033632";
const whatsappHref = "https://wa.me/79186577650";

const directions: Record<DirectionId, {
  label: string;
  eyebrow: string;
  title: string;
  description: string;
  image: string;
  items: string[];
  meta: string;
}> = {
  women: { label: "Женское здоровье", eyebrow: "Гинекология", title: "Когда важно разобраться бережно и по делу.", description: "Консультация, УЗИ, диагностика и лечение в одном понятном маршруте — с врачом, к которому легко обратиться.", image: "/images/clinic-doctor.jpg", items: ["Приём гинеколога", "УЗИ малого таза", "Кольпоскопия", "Поддержка во время лечения"], meta: "Взрослые и дети" },
  men: { label: "Мужское здоровье", eyebrow: "Урология и андрология", title: "Конфиденциально. Внимательно. С результатом.", description: "Помогаем пройти диагностику и лечение без лишних поездок: от первой консультации до контрольного визита.", image: "/images/clinic-detail.jpg", items: ["Уролог-андролог", "Диагностика и анализы", "Оперативное лечение", "Сопровождение после"], meta: "Высшая категория · 25+ лет стажа" },
  diagnostics: { label: "Диагностика", eyebrow: "УЗИ и функциональная диагностика", title: "Сначала понять причину — потом выбирать лечение.", description: "УЗИ, ЭКГ, Эхо-КГ, Холтер, видеоларингоскопия и другие исследования помогают врачу видеть полную картину.", image: "/images/clinic-hero.jpg", items: ["УЗИ органов и систем", "ЭКГ и Эхо-КГ", "Холтер", "Лабораторные исследования"], meta: "Современная диагностика" },
  beauty: { label: "Кожа и эстетика", eyebrow: "Дерматология и косметология", title: "Уход, который начинается с консультации.", description: "От лечения кожи до эстетических процедур — без случайного набора услуг и лишних назначений.", image: "/images/clinic-detail-2.jpg", items: ["Дерматолог", "Аппаратные методики", "Пилинги и уходы", "Удаление новообразований"], meta: "План под вашу задачу" },
  family: { label: "Здоровье всей семьи", eyebrow: "Многопрофильный центр", title: "Один адрес для разных медицинских задач.", description: "Специалисты разных направлений, диагностика и лечение собраны в клинике на Гагарина — рядом с домом и привычным ритмом.", image: "/images/clinic-hero.jpg", items: ["Терапия и кардиология", "Неврология и ЛОР", "Эндокринология", "Проктология и хирургия"], meta: "28 специальностей" },
};

const directionTabs: Array<{ id: DirectionId; label: string }> = [
  { id: "women", label: "Женское здоровье" },
  { id: "men", label: "Мужское здоровье" },
  { id: "diagnostics", label: "Диагностика" },
  { id: "beauty", label: "Кожа и эстетика" },
  { id: "family", label: "Для всей семьи" },
];

const doctors = [
  { name: "Рудольф Казаров", role: "Главный врач · уролог-андролог", detail: "Высшая категория · стаж 26 лет", tone: "green" },
  { name: "Алан Киргуев", role: "Уролог-андролог", detail: "Высшая категория · стаж 25 лет", tone: "orange" },
  { name: "Александра Мамедова", role: "Гинеколог", detail: "Высшая категория · стаж 15 лет", tone: "pink" },
  { name: "Анна Липатова", role: "Косметолог · дерматовенеролог", detail: "Первая категория · стаж 25 лет", tone: "blue" },
];

const reviews = [
  { quote: "После обследования назначили время операции. После — сопровождение и контроль.", note: "Отзыв о маршруте в урологии", source: "Официальный сайт", href: "https://pokolenie-med.ru/", tone: "review-green" },
  { quote: "Очень приятное отношение: забота, тепло, внимание, бережное отношение к пациенту.", note: "Отзыв о работе медицинских сестёр", source: "Официальный сайт", href: "https://pokolenie-med.ru/", tone: "review-yellow" },
  { quote: "Обследование было в полном объёме. К данному врачу приду ещё.", note: "Отзыв об УЗИ", source: "НаПоправку", href: "https://napopravku.ru/krasnodar/clinics/meditsinskij-tsentr-novoe-pokolenie/", tone: "review-pink" },
];

const faqs = [
  { question: "Как понять, к какому врачу записаться?", answer: "Позвоните в клинику или оставьте заявку. Администратор уточнит задачу и подберёт специалиста, чтобы вы не тратили время на лишние записи." },
  { question: "Можно ли пройти диагностику в тот же день?", answer: "В клинике доступны УЗИ и функциональная диагностика. Возможность пройти исследование в день приёма зависит от расписания — администратор подскажет ближайшее время." },
  { question: "Принимают ли врачи детей?", answer: "В открытой карточке клиники указано, что центр принимает взрослых и детей. Конкретный возраст и направление лучше уточнить при записи." },
  { question: "Как записаться без звонка?", answer: "Оставьте заявку в форме — в демонстрационной версии она показывает сценарий записи. Для реальной записи можно сразу написать в WhatsApp или позвонить в регистратуру." },
];

function Arrow() { return <span className="arrow" aria-hidden="true">↗</span>; }

function Logo({ light = false }: { light?: boolean }) {
  return <span className={`brand-lockup ${light ? "brand-lockup-light" : ""}`}><span className="brand-mark"><img src="/images/clinic-logo.jpg" alt="" /></span><span className="brand-name"><strong>Новое поколение</strong><small>медицинский центр</small></span></span>;
}

export default function Home() {
  const [activeDirection, setActiveDirection] = useState<DirectionId>("women");
  const [bookingOpen, setBookingOpen] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);
  const [submitted, setSubmitted] = useState(false);
  useEffect(() => {
    document.body.style.overflow = bookingOpen ? "hidden" : "";
    const handleEscape = (event: KeyboardEvent) => { if (event.key === "Escape") setBookingOpen(false); };
    window.addEventListener("keydown", handleEscape);
    return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", handleEscape); };
  }, [bookingOpen]);
  const selectedDirection = directions[activeDirection];
  const scrollTo = (id: string) => { setMobileMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); };
  const openBooking = () => { setSubmitted(false); setBookingOpen(true); };

  return (
    <main className="site-shell" id="top">
      <div className="utility-bar"><div className="container utility-inner"><span>Краснодар · Фестивальный район</span><span className="utility-separator">●</span><span>Пн–пт 08:00–20:00 · сб 08:00–18:00 · вс 08:00–14:00</span><a href={phoneHref}>Позвонить в клинику <Arrow /></a></div></div>
      <header className="site-header"><div className="container header-inner"><button className="brand-button" onClick={() => scrollTo("top")} aria-label="Новое поколение, на главную"><Logo /></button><nav className={`main-nav ${mobileMenuOpen ? "main-nav-open" : ""}`} aria-label="Основная навигация"><button onClick={() => scrollTo("start")}>С чего начать</button><button onClick={() => scrollTo("directions")}>Направления</button><button onClick={() => scrollTo("doctors")}>Врачи</button><button onClick={() => scrollTo("contacts")}>Контакты</button></nav><div className="header-actions"><a className="header-phone" href={phoneHref}>{phone}</a><button className="button button-primary header-cta" onClick={openBooking}>Записаться <Arrow /></button><button className="menu-toggle" onClick={() => setMobileMenuOpen((value) => !value)} aria-label={mobileMenuOpen ? "Закрыть меню" : "Открыть меню"} aria-expanded={mobileMenuOpen}><span /><span /></button></div></div></header>
      <section className="hero-section"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow eyebrow-light"><span className="eyebrow-dot" /> Для взрослых и детей</div><h1>Здоровье, которому можно доверить <em>семью.</em></h1><p className="hero-lead">Многопрофильный медицинский центр на Гагарина: специалисты, диагностика и лечение — в одном понятном маршруте.</p><div className="hero-actions"><button className="button button-lime" onClick={openBooking}>Подобрать специалиста <Arrow /></button><button className="button button-ghost-light" onClick={() => scrollTo("directions")}>Посмотреть направления <span>↓</span></button></div><div className="hero-microcopy"><span className="micro-icon">+</span><span><strong>Начните с вопроса.</strong> Администратор поможет понять, с чего лучше начать.</span></div></div><div className="hero-visual"><div className="hero-image-frame"><img src="/images/clinic-hero.jpg" alt="Ресепшен медицинского центра Новое поколение" /><div className="hero-image-overlay" /><div className="hero-caption"><span>Краснодар</span><strong>ул. Космонавта Гагарина, 124</strong></div></div><div className="hero-card"><span className="hero-card-number">01</span><strong>Один адрес.<br />Много решений.</strong><span className="hero-card-rule" /><small>Консультация · диагностика · лечение</small></div></div></div></section>
      <section className="proof-strip" aria-label="Факты о клинике"><div className="container proof-grid"><div className="proof-item"><strong>28</strong><span>специальностей<br />в одном центре</span></div><div className="proof-item"><strong>4,5–4,6</strong><span>рейтинг на картах<br />и медсервисах</span></div><div className="proof-item"><strong>7 дней</strong><span>в неделю<br />на связи с пациентами</span></div><div className="proof-item proof-last"><span className="proof-symbol">✦</span><span>Фестивальный<br />район Краснодара</span><Arrow /></div></div></section>
      <section className="section start-section" id="start"><div className="container"><div className="section-heading section-heading-split"><div><div className="eyebrow"><span className="eyebrow-dot" /> С чего начать</div><h2>Не ищите врача.<br /><em>Опишите задачу.</em></h2></div><p>Собрали основные сценарии, с которыми пациенты приходят в клинику. Выберите свой — и мы покажем ближайший понятный шаг.</p></div><div className="journey-grid"><button className="journey-card journey-card-green" onClick={() => { setActiveDirection("diagnostics"); scrollTo("directions"); }}><span className="journey-index">01</span><span className="journey-icon">◌</span><strong>Хочу пройти<br />обследование</strong><small>УЗИ · анализы · диагностика</small><Arrow /></button><button className="journey-card journey-card-yellow" onClick={() => { setActiveDirection("family"); scrollTo("directions"); }}><span className="journey-index">02</span><span className="journey-icon">⌁</span><strong>Нужен врач<br />по симптомам</strong><small>Консультация · план лечения</small><Arrow /></button><button className="journey-card journey-card-pink" onClick={() => { setActiveDirection("beauty"); scrollTo("directions"); }}><span className="journey-index">03</span><span className="journey-icon">✧</span><strong>Хочу заняться<br />кожей</strong><small>Дерматология · косметология</small><Arrow /></button><button className="journey-card journey-card-blue" onClick={() => { setActiveDirection("family"); scrollTo("directions"); }}><span className="journey-index">04</span><span className="journey-icon">＋</span><strong>Ищу клинику<br />для семьи</strong><small>Взрослые · дети · специалисты</small><Arrow /></button></div></div></section>
      <section className="section directions-section" id="directions"><div className="container"><div className="section-heading section-heading-split"><div><div className="eyebrow"><span className="eyebrow-dot" /> Направления</div><h2>Всё начинается<br />с <em>точного</em> маршрута.</h2></div><p>Клиника объединяет приём врачей, инструментальную диагностику и лечение. Не нужно собирать маршрут по разным адресам.</p></div><div className="direction-tabs" role="tablist" aria-label="Направления клиники">{directionTabs.map((tab) => <button key={tab.id} role="tab" aria-selected={activeDirection === tab.id} className={activeDirection === tab.id ? "direction-tab-active" : ""} onClick={() => setActiveDirection(tab.id)}>{tab.label}<Arrow /></button>)}</div><div className="direction-panel"><div className="direction-photo"><img src={selectedDirection.image} alt={selectedDirection.title} /><div className="photo-wash" /><div className="photo-label"><span>Новое поколение</span><strong>{selectedDirection.meta}</strong></div></div><div className="direction-copy"><div className="eyebrow"><span className="eyebrow-dot" /> {selectedDirection.eyebrow}</div><h3>{selectedDirection.title}</h3><p>{selectedDirection.description}</p><ul className="direction-list">{selectedDirection.items.map((item) => <li key={item}><span>✓</span>{item}</li>)}</ul><button className="button button-outline" onClick={openBooking}>Обсудить задачу <Arrow /></button></div></div><div className="other-directions"><span>Также в клинике</span><div><span>Неврология</span><span>Кардиология</span><span>ЛОР</span><span>Эндокринология</span><span>Проктология</span><span>Хирургия</span><span>Аллергология</span></div></div></div></section>
      <section className="section team-section" id="doctors"><div className="container team-grid"><div className="team-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Команда</div><h2>Врач — это<br /><em>партнёр</em> по пути.</h2><p>На сайте клиники уже есть сильный состав специалистов. Мы показываем его так, чтобы пациенту было проще выбрать по задаче, опыту и ощущению доверия.</p><div className="team-note"><span>✦</span><span>Высшая квалификация, кандидаты наук и 25+ лет практики у специалистов клиники.</span></div><button className="button button-light" onClick={openBooking}>Подобрать врача <Arrow /></button></div><div className="doctor-list">{doctors.map((doctor, index) => <article className={`doctor-card doctor-${doctor.tone}`} key={doctor.name}><div className="doctor-avatar"><span>0{index + 1}</span><b>{doctor.name.split(" ").map((part) => part[0]).join("")}</b></div><div><h3>{doctor.name}</h3><p>{doctor.role}</p><small>{doctor.detail}</small></div><Arrow /></article>)}</div></div></section>
      <section className="section steps-section"><div className="container"><div className="section-heading centered-heading"><div className="eyebrow"><span className="eyebrow-dot" /> Как это работает</div><h2>Простой путь<br /><em>до следующего шага.</em></h2></div><div className="steps-grid"><div className="step-card"><span>01</span><strong>Описываете задачу</strong><p>По телефону, в WhatsApp или в форме на сайте.</p></div><div className="step-card"><span>02</span><strong>Получаете маршрут</strong><p>Администратор подбирает направление и ближайшее время.</p></div><div className="step-card"><span>03</span><strong>Приходите в клинику</strong><p>Гагарина, 124. Парковка для гостей — рядом.</p></div></div></div></section>
      <section className="section review-section"><div className="container"><div className="section-heading section-heading-split review-heading"><div><div className="eyebrow"><span className="eyebrow-dot" /> Голос пациентов</div><h2>Доверие,<br /><em>которое слышно.</em></h2></div><div className="review-score"><strong>4,5–4,6</strong><span>рейтинг клиники<br />на картах и сервисах</span></div></div><div className="reviews-grid">{reviews.map((review) => <article className={`review-card ${review.tone}`} key={review.quote}><span className="review-source">{review.source}</span><p>“{review.quote}”</p><div className="review-footer"><span>{review.note}</span><a href={review.href} target="_blank" rel="noreferrer">Читать источник <Arrow /></a></div></article>)}</div></div></section>
      <section className="section faq-section" id="faq"><div className="container faq-grid"><div className="faq-intro"><div className="eyebrow"><span className="eyebrow-dot" /> Перед визитом</div><h2>Ответы,<br /><em>которые</em><br />помогают решиться.</h2><p>Не нашли свой вопрос? Позвоните — администратор поможет сориентироваться.</p><a href={phoneHref} className="button button-outline">Позвонить в клинику <Arrow /></a></div><div className="faq-list">{faqs.map((faq, index) => <div className={`faq-item ${openFaq === index ? "faq-open" : ""}`} key={faq.question}><button onClick={() => setOpenFaq(openFaq === index ? -1 : index)} aria-expanded={openFaq === index}><span>{faq.question}</span><b>{openFaq === index ? "−" : "+"}</b></button><div className="faq-answer"><p>{faq.answer}</p></div></div>)}</div></div></section>
      <section className="contact-section" id="contacts"><div className="container contact-grid"><div className="contact-main"><div className="eyebrow eyebrow-light"><span className="eyebrow-dot" /> Ваш следующий шаг</div><h2>Начните с разговора<br /><em>о том, что важно вам.</em></h2><p>Мы ответим на вопросы, предложим ближайшее время и подскажем, как подготовиться к визиту.</p><div className="contact-actions"><button className="button button-lime" onClick={openBooking}>Оставить заявку <Arrow /></button><a className="button button-ghost-light" href={whatsappHref} target="_blank" rel="noreferrer">Написать в WhatsApp <Arrow /></a></div></div><div className="contact-card"><div className="contact-card-top"><span className="contact-label">На карте</span><span className="contact-pin">⌖</span></div><strong>ул. Космонавта<br />Гагарина, 124</strong><span>350049 · Краснодар<br />Фестивальный район</span><div className="map-links"><a href="https://2gis.ru/krasnodar/firm/70000001023930438" target="_blank" rel="noreferrer">2ГИС <Arrow /></a><a href="https://yandex.ru/maps/?text=Краснодар%20ул.%20Космонавта%20Гагарина%20124" target="_blank" rel="noreferrer">Яндекс <Arrow /></a><a href="https://www.google.com/maps/search/?api=1&query=Новое+поколение,+ул.+Космонавта+Гагарина,+124,+Краснодар" target="_blank" rel="noreferrer">Google <Arrow /></a></div></div></div></section>
      <footer className="site-footer"><div className="container footer-top"><div><Logo light /><p className="footer-tagline">Для вашего здоровья.<br />Краснодар · Гагарина, 124</p></div><div className="footer-columns"><div><span className="footer-label">Навигация</span><button onClick={() => scrollTo("start")}>С чего начать</button><button onClick={() => scrollTo("directions")}>Направления</button><button onClick={() => scrollTo("doctors")}>Врачи</button><button onClick={() => scrollTo("faq")}>Вопросы</button></div><div><span className="footer-label">Связь</span><a href={phoneHref}>{phone}</a><a href={whatsappHref} target="_blank" rel="noreferrer">WhatsApp</a><a href="mailto:info@pokolenie-med.ru">info@pokolenie-med.ru</a></div><div><span className="footer-label">Режим работы</span><span>Пн–пт · 08:00–20:00</span><span>Сб · 08:00–18:00</span><span>Вс · 08:00–14:00</span></div></div></div><div className="container footer-bottom"><span>ООО «МедЗдрав» · Информация носит справочный характер</span><span>Демонстрационная концепция нового сайта</span></div></footer>
      <div className="mobile-sticky-cta"><a href={phoneHref}>Позвонить</a><button onClick={openBooking}>Записаться <Arrow /></button></div>
      {bookingOpen && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setBookingOpen(false); }}><div className="booking-modal" role="dialog" aria-modal="true" aria-labelledby="booking-title"><button className="modal-close" onClick={() => setBookingOpen(false)} aria-label="Закрыть">×</button>{submitted ? <div className="success-state"><span className="success-icon">✓</span><div className="eyebrow"><span className="eyebrow-dot" /> Заявка подготовлена</div><h2>Осталось<br /><em>связаться.</em></h2><p>В рабочей версии сайта заявка уйдёт администратору. В демо-версии можно сразу позвонить или написать в WhatsApp.</p><div className="success-actions"><a className="button button-primary" href={phoneHref}>Позвонить <Arrow /></a><a className="button button-outline" href={whatsappHref} target="_blank" rel="noreferrer">WhatsApp <Arrow /></a></div></div> : <><div className="eyebrow"><span className="eyebrow-dot" /> Запись на приём</div><h2 id="booking-title">Начнём<br /><em>с задачи.</em></h2><p>Оставьте контакты — администратор подскажет направление и ближайшее время.</p><form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><label>Имя<input name="name" required placeholder="Как к вам обращаться" /></label><label>Телефон<input name="phone" type="tel" required placeholder="+7 (___) ___-__-__" /></label><label>Что вас интересует?<select name="direction" defaultValue=""><option value="" disabled>Выберите направление</option><option>Женское здоровье</option><option>Мужское здоровье</option><option>Диагностика</option><option>Кожа и эстетика</option><option>Для всей семьи</option><option>Пока не знаю</option></select></label><label className="consent"><input type="checkbox" required /> <span>Согласен на обработку персональных данных</span></label><button type="submit" className="button button-primary form-submit">Отправить заявку <Arrow /></button></form></>}</div></div>}
    </main>
  );
}
