"use client";

import { useEffect, useState } from "react";

type ServiceTab = "aesthetics" | "surgery" | "health" | "spa";

const serviceTabs: Array<{ id: ServiceTab; label: string }> = [
  { id: "aesthetics", label: "Косметология" },
  { id: "surgery", label: "Хирургия" },
  { id: "health", label: "Поликлиника" },
  { id: "spa", label: "SPA и уход" },
];

const serviceContent: Record<ServiceTab, { eyebrow: string; title: string; description: string; image: string; items: string[] }> = {
  aesthetics: { eyebrow: "Эстетическая медицина", title: "Уход, который начинается с диагностики", description: "Врач-косметолог помогает собрать персональный план: от мягких уходовых процедур до аппаратных и инъекционных методик.", image: "/images/clinic-03.webp", items: ["Аппаратная косметология", "Инъекционные протоколы", "Пилинги и уходы", "Трихология и дерматология"] },
  surgery: { eyebrow: "Пластическая и общая хирургия", title: "Спокойствие на каждом этапе", description: "Консультация, подготовка, операция и восстановление в одной клинике — с командой врачей и круглосуточным вниманием к пациенту.", image: "/images/clinic-01.webp", items: ["Пластика лица и тела", "Пластика груди", "Интимная хирургия", "Реабилитация и стационар"] },
  health: { eyebrow: "Медицина полного цикла", title: "Когда нужен не один специалист, а команда", description: "Приём врачей, диагностика и лечение собраны в одном маршруте — без поездок по разным клиникам и потери времени.", image: "/images/clinic-02.webp", items: ["Гинекология и урология", "Терапия и кардиология", "Неврология и ортопедия", "УЗИ и диагностика"] },
  spa: { eyebrow: "Пространство восстановления", title: "Красота, в которой можно выдохнуть", description: "SPA-ритуалы, массаж и эстетический уход помогают замедлиться, восстановить силы и почувствовать себя лучше.", image: "/images/clinic-04.webp", items: ["Массаж и SPA-программы", "Эстетический уход", "Коррекция фигуры", "Подарочные сертификаты"] },
};

const faqs = [
  { question: "Как понять, к какому специалисту записаться?", answer: "Оставьте заявку с описанием задачи. Администратор уточнит детали и подберёт подходящего врача или косметолога, чтобы первый визит был максимально полезным." },
  { question: "Можно ли пройти диагностику и лечение в одном месте?", answer: "Да. В клинике есть поликлиника, специалисты разных направлений, УЗИ и диагностические маршруты. На консультации врач подскажет, что действительно необходимо." },
  { question: "Как проходит консультация по пластической хирургии?", answer: "Врач обсуждает задачу, возможные методы, ограничения, подготовку и восстановление. После консультации у вас остаётся понятный план действий и время на решение." },
  { question: "Как записаться на косметологию?", answer: "Позвоните по номеру клиники или оставьте заявку на сайте. Мы свяжемся в рабочее время и предложим ближайшие слоты к нужному специалисту." },
];

function ArrowUpRight() { return <span aria-hidden="true">↗</span>; }

export default function Home() {
  const [activeTab, setActiveTab] = useState<ServiceTab>("aesthetics");
  const [bookingOpen, setBookingOpen] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [submitted, setSubmitted] = useState(false);

  useEffect(() => {
    document.body.style.overflow = bookingOpen ? "hidden" : "";
    const handleEscape = (event: KeyboardEvent) => { if (event.key === "Escape") setBookingOpen(false); };
    window.addEventListener("keydown", handleEscape);
    return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", handleEscape); };
  }, [bookingOpen]);

  const activeContent = serviceContent[activeTab];
  const scrollTo = (id: string) => { setMobileMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); };
  const openBooking = () => { setSubmitted(false); setBookingOpen(true); };

  return (
    <main className="site-shell">
      <div className="topline"><div className="container topline-inner"><span>Краснодар · Фестивальный район</span><span>Ежедневно с 08:00 до 21:00</span></div></div>
      <header className="site-header"><div className="container header-inner">
        <button className="brand" onClick={() => scrollTo("top")} aria-label="Шале Сантэ, на главную"><span className="brand-mark">CS</span><span><strong>Chalet Sante</strong><small>дом здоровья</small></span></button>
        <nav className={`desktop-nav ${mobileMenuOpen ? "is-open" : ""}`} aria-label="Основная навигация"><button onClick={() => scrollTo("directions")}>Направления</button><button onClick={() => scrollTo("aesthetics")}>Косметология</button><button onClick={() => scrollTo("clinic")}>О клинике</button><button onClick={() => scrollTo("answers")}>Вопросы</button></nav>
        <div className="header-actions"><a className="phone-link" href="tel:+78001009898">+7 (800) 100-98-98</a><button className="button button-dark header-button" onClick={openBooking}>Записаться <ArrowUpRight /></button><button className="menu-toggle" onClick={() => setMobileMenuOpen((value) => !value)} aria-label={mobileMenuOpen ? "Закрыть меню" : "Открыть меню"} aria-expanded={mobileMenuOpen}><span /><span /></button></div>
      </div></header>

      <section className="hero" id="top"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> 19 лет заботы о пациентах</div><h1>Дом здоровья, где красота становится спокойствием.</h1><p className="hero-lead">Многопрофильная клиника в Краснодаре: врачи, хирургия, косметология и восстановление — в одном продуманном маршруте.</p><div className="hero-actions"><button className="button button-accent" onClick={openBooking}>Подобрать специалиста <ArrowUpRight /></button><button className="text-button" onClick={() => scrollTo("directions")}>Смотреть направления <span>↓</span></button></div><div className="hero-note"><span className="note-avatar">19</span><span><strong>19 лет</strong> помогаем сохранять здоровье, молодость и уверенность.</span></div></div><div className="hero-visual"><div className="hero-image-wrap"><img src="/images/clinic-04.webp" alt="Ресепшен клиники Chalet Sante" className="hero-image" /><div className="image-caption"><span>Краснодар</span><strong>Красных Партизан, 238</strong></div></div><div className="hero-float-card"><span className="float-label">Маршрут пациента</span><strong>Сначала — понять.<br />Потом — действовать.</strong><span className="float-line" /><span className="float-small">Консультация · план · сопровождение</span></div><div className="hero-side-label">CLINIC · BEAUTY · CARE</div></div></div></section>

      <section className="proof-bar"><div className="container proof-grid"><div className="proof-item"><strong>41</strong><span>врач и специалист<br />в команде</span></div><div className="proof-item"><strong>1 300+</strong><span>отзывов пациентов<br />на независимых площадках</span></div><div className="proof-item"><strong>4</strong><span>основных<br />направления</span></div><div className="proof-item proof-highlight"><span className="proof-star">✦</span><span>Выбор пациентов<br />Краснодара</span><ArrowUpRight /></div></div></section>

      <section className="section directions" id="directions"><div className="container"><div className="section-heading split-heading"><div><div className="eyebrow"><span className="eyebrow-dot" /> Ваша задача — наш маршрут</div><h2>Всё, что нужно для здоровья и красоты.</h2></div><p>От первой консультации до восстановления — команда клиники остаётся рядом на каждом этапе.</p></div><div className="service-tabs" role="tablist" aria-label="Направления клиники">{serviceTabs.map((tab) => <button key={tab.id} role="tab" aria-selected={activeTab === tab.id} className={activeTab === tab.id ? "active" : ""} onClick={() => setActiveTab(tab.id)}><span>{tab.label}</span><ArrowUpRight /></button>)}</div><div className="service-panel"><div className="service-panel-image"><img src={activeContent.image} alt={activeContent.title} /><div className="panel-image-tag">Chalet Sante / {activeContent.eyebrow}</div></div><div className="service-panel-copy"><div className="eyebrow"><span className="eyebrow-dot" /> {activeContent.eyebrow}</div><h3>{activeContent.title}</h3><p>{activeContent.description}</p><ul className="service-list">{activeContent.items.map((item) => <li key={item}><span>✓</span>{item}</li>)}</ul><button className="button button-outline" onClick={openBooking}>Обсудить задачу <ArrowUpRight /></button></div></div></div></section>

      <section className="section aesthetics-section" id="aesthetics"><div className="container aesthetics-grid"><div className="aesthetics-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Фокус клиники</div><h2>Косметология без перегруза.</h2><p className="large-copy">Мы не продаём набор процедур. Врач сначала видит картину целиком, объясняет возможные решения и собирает программу под вас.</p><div className="feature-list"><div><span>01</span><strong>Диагностика</strong><p>Понимаем состояние кожи, цели и ограничения.</p></div><div><span>02</span><strong>План</strong><p>Выбираем только те методики, которые действительно нужны.</p></div><div><span>03</span><strong>Сопровождение</strong><p>Остаёмся на связи до понятного, ожидаемого результата.</p></div></div><button className="button button-light" onClick={openBooking}>Получить консультацию <ArrowUpRight /></button></div><div className="aesthetics-collage"><div className="collage-main"><img src="/images/clinic-03.webp" alt="Косметологическая процедура" /></div><div className="collage-small"><img src="/images/clinic-01.webp" alt="Консультация перед операцией" /></div><div className="collage-badge"><span>CS</span><strong>care<br />with<br />clarity</strong></div></div></div></section>

      <section className="section clinic-section" id="clinic"><div className="container clinic-grid"><div className="clinic-image-block"><img src="/images/clinic-02.webp" alt="Операционная клиники Chalet Sante" /><div className="clinic-image-label"><span>01</span><span>Внутри клиники</span></div></div><div className="clinic-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Почему нам доверяют</div><h2>Современная медицина с человеческим лицом.</h2><p>«Шале Сантэ» — это место, где технологичность не отменяет тёплого отношения. Здесь можно пройти путь от диагностики до результата в спокойной и безопасной среде.</p><div className="clinic-points"><div><span className="point-icon">✦</span><div><strong>Один адрес — много решений</strong><p>Поликлиника, хирургия, косметология, SPA и диагностика.</p></div></div><div><span className="point-icon">✦</span><div><strong>Команда экспертов</strong><p>Врачи разных направлений работают как единая команда.</p></div></div><div><span className="point-icon">✦</span><div><strong>Внимание к деталям</strong><p>От первого звонка до контрольного визита после процедуры.</p></div></div></div><button className="text-button underline-button" onClick={() => scrollTo("answers")}>Узнать больше о клинике <ArrowUpRight /></button></div></div></section>

      <section className="section review-section"><div className="container"><div className="section-heading split-heading review-heading"><div><div className="eyebrow"><span className="eyebrow-dot" /> Голос пациентов</div><h2>Важные слова<br /><em>после</em> результата.</h2></div><div className="review-heading-side"><span className="review-mark">“</span><p>Больше 1 300 отзывов на независимых площадках — пациенты возвращаются к своим врачам и рекомендуют клинику близким.</p></div></div><div className="reviews-grid"><article className="review-card featured-review"><span className="review-platform">ПРОДОКТОРОВ</span><p>«Очень комфортно находиться в клинике. Врачи высочайшего уровня, профессионалы, которым доверяешь полностью.»</p><div className="review-author"><span>А</span><div><strong>Пациентка клиники</strong><small>отзыв о хирургическом отделении</small></div></div></article><article className="review-card"><span className="review-platform">ЯНДЕКС КАРТЫ</span><p>«Косметолог внимательная, всё объясняет и даёт рекомендации. После чистки минимальные покраснения — результатом довольна.»</p><div className="review-author"><span>Е</span><div><strong>Елена</strong><small>отзыв о косметологии</small></div></div></article><article className="review-card"><span className="review-platform">НАПОПРАВКУ</span><p>«Уютная клиника, доброжелательный персонал, отличные доктора. В помещениях чисто и просторно.»</p><div className="review-author"><span>О</span><div><strong>Олеся</strong><small>отзыв о клинике</small></div></div></article></div></div></section>

      <section className="section faq-section" id="answers"><div className="container faq-grid"><div className="faq-intro"><div className="eyebrow"><span className="eyebrow-dot" /> Перед визитом</div><h2>Ответы,<br /><em>которые</em> помогают решиться.</h2><p>Если не нашли свой вопрос — позвоните нам. Администратор подскажет, с чего начать.</p><a className="button button-outline" href="tel:+78001009898">Позвонить в клинику <ArrowUpRight /></a></div><div className="faq-list">{faqs.map((faq, index) => <div className={`faq-item ${openFaq === index ? "open" : ""}`} key={faq.question}><button onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index}><span>{faq.question}</span><b>{openFaq === index ? "−" : "+"}</b></button><div className="faq-answer"><p>{faq.answer}</p></div></div>)}</div></div></section>

      <section className="contact-cta"><div className="container contact-cta-inner"><div><div className="eyebrow"><span className="eyebrow-dot" /> Ваш следующий шаг</div><h2>Начните с разговора<br /><em>о том, что важно вам.</em></h2></div><div className="contact-cta-action"><p>Администратор свяжется с вами, уточнит задачу и подберёт специалиста.</p><button className="button button-light" onClick={openBooking}>Оставить заявку <ArrowUpRight /></button></div></div></section>

      <footer className="site-footer"><div className="container footer-top"><div className="footer-brand"><span className="brand-mark">CS</span><div><strong>Chalet Sante</strong><small>дом здоровья</small></div></div><div className="footer-columns"><div><span className="footer-label">Навигация</span><button onClick={() => scrollTo("directions")}>Направления</button><button onClick={() => scrollTo("aesthetics")}>Косметология</button><button onClick={() => scrollTo("clinic")}>О клинике</button></div><div><span className="footer-label">Контакты</span><a href="tel:+78001009898">+7 (800) 100-98-98</a><a href="https://yandex.ru/maps/org/chalet_sante/1213138791/" target="_blank" rel="noreferrer">Красных Партизан, 238 ↗</a><span>Краснодар</span></div><div><span className="footer-label">Режим работы</span><span>Ежедневно</span><span>08:00 — 21:00</span><a href="https://xn----7sbbs3ap0ak0c4c.xn--p1ai/" target="_blank" rel="noreferrer">Официальный сайт ↗</a></div></div></div><div className="container footer-bottom"><span>© 2026 Chalet Sante</span><span>Медицинская информация требует консультации специалиста.</span><a href="#top">Наверх ↑</a></div></footer>

      <div className="mobile-sticky-cta"><a href="tel:+78001009898">Позвонить</a><button onClick={openBooking}>Записаться</button></div>
      {bookingOpen && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setBookingOpen(false); }}><div className="booking-modal" role="dialog" aria-modal="true" aria-labelledby="booking-title"><button className="modal-close" onClick={() => setBookingOpen(false)} aria-label="Закрыть форму">×</button>{!submitted ? <><div className="eyebrow"><span className="eyebrow-dot" /> Консультация</div><h2 id="booking-title">Подберём ваш<br /><em>маршрут.</em></h2><p>Оставьте контакты — администратор свяжется с вами в рабочее время.</p><form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><label>Ваше имя<input required name="name" placeholder="Как к вам обращаться?" /></label><label>Телефон<input required name="phone" type="tel" placeholder="+7 (___) ___-__-__" /></label><label>Что вас интересует<select name="direction" defaultValue=""><option value="" disabled>Выберите направление</option><option>Косметология</option><option>Пластическая хирургия</option><option>Поликлиника и диагностика</option><option>SPA и уход</option><option>Пока не знаю</option></select></label><label className="consent"><input required type="checkbox" /> <span>Соглашаюсь на обработку персональных данных</span></label><button className="button button-dark form-submit" type="submit">Отправить заявку <ArrowUpRight /></button></form></> : <div className="success-state"><span className="success-icon">✓</span><div className="eyebrow"><span className="eyebrow-dot" /> Заявка отправлена</div><h2>Спасибо.<br /><em>Мы свяжемся с вами.</em></h2><p>Если вопрос срочный, позвоните по номеру клиники — администратор ответит быстрее.</p><a className="button button-dark" href="tel:+78001009898">Позвонить в клинику <ArrowUpRight /></a></div>}</div></div>}
    </main>
  );
}
